source 'https://rubygems.org'

gem 'dashing'
gem 'google-api-client', '~> 0.7.1'
gem 'json'
gem 'uptimerobot'
gem 'puma'
gem 'rest-client'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
